### ISSUE TITLE
Keep the state of the other activities in a global place

### ISSUE THREAD

**Issue by mlegenhausen** [itm/wiseui#19]
Currently when switching the tabs the state of the other tabs is not stored. But the WiseUI has to act like a desktop app where you can switch between the different parts.

A solution would be a WiseUiPlace that contain all other Places. A generic class has to be created that can store other places and stores the current active state.

**Comment by whantana** [comment]
I think you are referring to the obvious bug appearing on the Reservation/Experimentation views. When a user swiches back and forth between those views some panels are getting re-filled with data (such nodes or experiments). This happens because of the repeating execution of the start() method implemented on each activity class.

First thing that comes to mind as a possible solution is the use of the mayStop() method (see Activity javadoc) in order to keep track of the activity state but that might require a static state holder. Yet, I find that this solution might not be architectually sound because it resembles the use of a global variable. So it might lead to bad design.

So please would you mind elaborating on this WiseUiPlace idea.

**Comment by soenkenils** [comment]
Actually, using a composite place and thus establishing a place hierarchy (via delegation) is the only way I can think of at the moment to solve this navigation issue (handling the state of multiple panels in the same window).

Google also recommends this strategy. Please take a look at http://code.google.com/webtoolkit/doc/latest/DevGuideMvpActivitiesAndPlaces.html, section "How to navigate".

**Comment by whantana** [comment]
So we need to somehow "encode" an activity's state and place it in the place token ? So even if we switch between places or hit refresh the state of the activity is retrievable through the place token ( the place URL ? ) right ?

**Comment by mlegenhausen** [comment]
Right, everything you store in the Place can be restored, when the user hits the refresh button. To persist something in the place (add the new Place to the URL) you have to use the PlaceController's goTo method. This initiates to reinitialize the activities with the new place given to the goTo method. This looks like a refresh but only the activites are reloaded, the rest of the app stays in the state before.

I have created a KeyValuePlace. With which you can easily store String values. For the serialisation of the object there is no general approach. Take a look at the TestbedSelectionPlace.

The place activity concept can be a little confusing.

**Comment by mlegenhausen** [comment]
The global place (WiseUiPlace) is now integrated and working. There are some optimizations to do, but it looks good at the moment.

**Comment by mlegenhausen** [comment]
There is currently a lot of boiler plate Code in the WiseUiPlace. This can maybe replaced by defered binding.

**Comment by soenkenils** [comment]
Ok, this seems to work. For the time being we'll leave it like that. We can optimize this for M2.
