### ISSUE TITLE
Confidential reservation data / View

### ISSUE THREAD

**Issue by iogakos** [itm/wiseui#46]
Should we have a separate view for displaying confidential reservations? 

What i am actually trying to do, is to insert a 'delete reservation' button in the popUp dialog when double-clicking on a reservation. Considering the appointments rendered in the calendar are all public reservation data, even if the user has already logged in, he will not be able to delete the reservation because of the missing reservation keys.

From my point of view, i can think of three possible solutions which i would like to share:
1. When a (logged in) user tries to delete a reservation, fetch the secret reservation key on request for each reservation by performing an equals check to the reservation parameters returned from server or better perform this check on the server. This might be an overhead when a user owns a very large number of reservations (thousands) but for now i cannot think of such a use case scenario.
2. Create a distinct view like 'privateReservationsView' using a toggle button between public and private. This button should be enabled only if the user has logged in to at least one testbed. If the user switches to the private reservations' view then an RPC will be taking place, asking the server for the confidential reservation data of the current user. This requires to introduce two new DTOs, the ConfidentialReservationData and Data to keep correspondence with the RS API.
3. If the user has logged in to at least one testbed, after rendering all public reservation data, delete all appointments owned by this user and re-request them by using the getConfidentialReservationData of the RS API. This requires, with high-possibility if i am thinking it right, a hash map for keeping entries for appointments and their secretReservationKeys.

**Comment by danbim** [comment]
Obviously the APIs are not very nicely defined for this use-case. From the users point-of-view I think it would be the nicest to simply display the users' reservations in a different color than the others and to make the "delete reservation"-button available only in these colored reservations. Therefore, I don't really like the second approach as this would change the UI behaviour because of an API shortcoming.

My proposal would be to first fetch the public reservations, then fetch the private ones and map them onto each other (by comparing their parameters as proposed in number one of your solutions) so that it is clear for the backend (frontend?) which reservation belongs to the user and which not, allowing to display the reservations as described above. If a user owns a lot of reservations I don't think this is a large performance bottleneck as pagination should do it's job here. If user experience would suffer as pagination in the calendar is to slow one could prefetch a week in advance and a week before.
